### ISSUE TITLE
Vue CLI 3.3 起 baseUrl 选项被改为 publicPath 了，请考虑兼容新的选项

### ISSUE THREAD

**Issue by sodatea** [longshihui/vue-cli-plugin-navigator#1]
https://github.com/longshihui/vue-cli-plugin-navigator/blob/fa5be8e3f89daa125ffa9c6a91bb7ae1c7fcd460/service/index.js#L68

https://github.com/vuejs/vue-cli/pull/3143

**Comment by longshihui** [comment]
好的 我看看
