### ISSUE TITLE
custom page path to open

### ISSUE THREAD

**Issue by IndexXuan** [longshihui/vue-cli-plugin-navigator#11]
Great Plugin !
the page path to open then table row click can be custom ? since Vue CLI support pages to custom filename, but the hard code here:

https://github.com/longshihui/vue-cli-plugin-navigator/blob/master/lib/HomepageDataCreator.js#L17

maybe user pass or read projectOptions.pages filename will be better ?
Thanks a lot !

**Comment by longshihui** [comment]
Thanks for your feedback!
I need some time to review your suggestions. 
because I have been busy recently...
